# -*- coding: utf-8 -*-
"""TR_AI_F_672021047_672021145_672021243.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_XHPoncdxIjYtVFDpgcZ4tHbMrry4OfL
"""

#install libraries
!pip install ultralytics -q #yolo
!pip install pyyaml -q #output

#import the libraries
from ultralytics import YOLO
import yaml
import cv2
from google.colab.patches import cv2_imshow

#instantiate the YOLO class
model = YOLO("yolov8n.pt")

model.predict("/content/dog.jpg", save = True, save_txt = True) #copy path, save --> to save results and make txt file

model.predict("/content/dog_and_bicycle.jpg", save = True, save_txt = True) #copy path, save --> to save results and make txt file